### ISSUE TITLE
When i restart Unity, i lost all the data in scriptable object

### ISSUE THREAD

**Issue by zekiaydin** [upscalebaby/generic-serializable-dictionary#21]
Hey,
First of all thank you for serializable dictionary, it helped me a lot on the project i am working on.

I am populating a generic dictionary in a scriptable object via script but when i close the project the content in dictionary are deleted. So i have to repopulate it everytime i open the project.

**Comment by upscalebaby** [comment]
Hey!

That shouldn't happened, could you try to go File -> Save Project and see if that persist the data?

Unity doesn't automatically save *.asset files and it's quite unintuitive that when you press Ctrl + S is the same as going File -> Save - which only saves the scene 😅

**Comment by zekiaydin** [comment]
File -> Save Project was the first and only thing that i tried, didn't work.

**Comment by upscalebaby** [comment]
Strange, I'm not doing any custom serialization (that's sort of the point of this repo). What Unity version are you using?

I work a full time Unity job these days but will try to reproduce this when I get time over.

**Comment by zekiaydin** [comment]
Currently i am using 2020.3.30f1.

**Comment by upscalebaby** [comment]
Hi again, could you verify that you get the expected behavior if you replace the serializable dictionary with a regular list first?

**Comment by zekiaydin** [comment]
I just checked and it works fine with a list.

**Comment by upscalebaby** [comment]
Cool thanks for getting back! This sounds serious I'll definitely have a look later today or tomorrow.

Could you share what data structures you're using for Key/Value pair?

**Comment by upscalebaby** [comment]
Hey again! I could not reproduce this issue on 2020.3.29f1, but I merged dev into master and created a new release that fixed some older non critical issues. Could you check if it fixes this for you?

https://github.com/upscalebaby/generic-serializable-dictionary/releases/tag/1.0.1

**Comment by zekiaydin** [comment]
Hi. It didn't solve it.

**Comment by zekiaydin** [comment]
Hello again,

I was going to try to populate scriptable objects in runtime so just added the builder scene as additive to my main scene and somehow it serialized it properly. I don’t think this problem is caused by my project because I tried it in a freshly created project before as well. The problem still continues if I try to run the builder scene directly too. I guess generic dictionary is working fine and something weird happens in Unity side. Thank you for your time and I think you can consider issue as closed.

**Comment by upscalebaby** [comment]
Thanks for getting back! 

Ok I think I know what happened, when you use SOs you can end up running into some edge cases with Unity's serialization system.

People typically fix this by using DontDestroyOnLoad attribute, or using additive scene loading and making sure not to unload the scene carrying the references to scriptable objects.

Another common pitfall is having a loading scene between gameplay scenes that doesn't reference much at all, and this end up unloading assets.

Closing this issue now but feel free to open up more if you encounter other problems (or even a discussion on this repos discussion page).

**Comment by upscalebaby** [comment]
Yes it was kind of a long shot, I'll try your exact unity editor version
and use that package you sent later today to try and reproduce.

/ E
